[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200

lib_deps = 
    gyverlibs/GyverTM1637 @ ^1.4.2
    gyverlibs/GyverSegment @ ^1.4.9
    gyverlibs/EncButton@^3.7.3
build_flags =
    -D buzz_pin=9
    -D rele_pin=12

    -D default_time=240
    -D default_step=30
    -D hold_step=300